import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from '@/contexts/providers';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Emrah Isović | Portfolio',
  description: 'Generated by create next app',
};

const interFont = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-bokor',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning
      data-scroll-behavior='smooth'
      className={interFont.variable}
    >
      <body
        suppressHydrationWarning
        className='font-main min-h-screen flex flex-col'
      >
        <Providers>
          <Header />
          <main className='bg-[var(--bg-main-light)] dark:bg-[var(--bg-main-dark)] flex-grow flex flex-col justify-center'>
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
